name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: self-hosted-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk maven unzip curl tar wget gnupg lsb-release apt-transport-https

    - name: Verify Java and Maven
      run: |
        java -version
        mvn -version

    - name: Build with Maven
      run: mvn compile

  security-check:
    runs-on: self-hosted-runner
    needs: compile

    steps:
    - uses: actions/checkout@v4

    - name: Trivy Installation
      run: |
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt update -y
        sudo apt install -y trivy

    - name: Trivy FS Scan
      run: trivy fs --format table -o fs-report.json .

    - name: Gitleaks Installation
      run: |
        curl -sL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz -o gitleaks.tar.gz
        tar -xzf gitleaks.tar.gz
        sudo mv gitleaks /usr/local/bin/
        gitleaks version

    - name: Gitleaks Code Scan
      run: gitleaks detect source . -r gitleaks-report.json -f json
